name: album-downloader
services:
  downloader:
    image: "ghcr.io/tal-sitton/album-downloader:latest"
    volumes:
      - ./config/arls.txt:/app/config/arls.txt
    environment:
      - ALBUMS_DOWNLOAD_MAX_WORKERS=5
      - STATUS_UPDATE_INTERVAL=5
      - OUTPUT_CLEAN_INETRVAL_MINUTES=60
      - DOWNLOADS_CLEAN_INETRVAL_MINUTES=60
    ports:
      - "80:80"
